### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by KingRizlaDK** [horhorou/stacklands.noMoreHungry#1]
Not sure if bug or not, but ive downloaded the plugin and installed it in the correct folder, but when i launch the game and start playing, hunger is still there and can still kill my villagers. ive installed 2 other plugins and they seem to work fine. it could just be that the game has been updated since the release.

**Comment by horhorou** [comment]
On it 👌

**Comment by horhorou** [comment]
**Mod updated** 

Enjoy 🎉
