### ISSUE TITLE
Baby increases food counter

### ISSUE THREAD

**Issue by KingRizlaDK** [horhorou/stacklands.noMoreHungry#2]
At the end of moon 6 my humans died of starvation. it worked so far but i did just have them do a baby so i am gonna test to see if it happens again both with and without making a baby. will comment with update later

**Comment by horhorou** [comment]
Thanks ! I'm on it 👌

**Comment by horhorou** [comment]
New version with bug fix https://github.com/horhorou/stacklands.noMoreHungry/releases/tag/R1.0.2
